"""Account-related models for authentication and user management."""

from common.service_connections.db_service.models.account_models.auth_user_model import (
    AuthUserModel,
    insert_auth_user,
    query_auth_user_by_email,
    query_auth_user_by_id,
    query_auth_user_by_username,
    query_all_auth_users,
    query_active_auth_users,
    update_auth_user_by_id,
    deactivate_auth_user,
)
from common.service_connections.db_service.models.account_models.user_model import (
    UserModel,
    insert_user,
    query_user_by_id,
    query_all_users,
    update_user_by_id,
    drop_user_by_id,
)
from common.service_connections.db_service.models.account_models.account_model import (
    AccountModel,
    AccountWithOwnerModel,
    insert_account,
    query_account_by_id,
    query_all_accounts,
    query_account_with_owner,
    update_account,
    deactivate_account,
    activate_account,
)
from common.service_connections.db_service.models.account_models.account_user_association_model import (
    AccountUserAssociationModel,
    AccountUserWithDetailsModel,
    BulkOperationResult,
    add_user_to_account,
    bulk_add_users_to_account,
    update_user_role,
    bulk_update_roles,
    set_primary_account,
    remove_user_from_account,
    bulk_remove_users,
    query_users_by_account,
    query_accounts_by_user,
    query_user_primary_account,
    query_user_role_in_account,
)
from common.service_connections.db_service.models.notification_models import (
    NotificationPreferenceModel,
    create_default_preferences,
    query_user_preferences,
    update_user_preferences,
    delete_user_preferences,
    get_users_with_preference_enabled,
    InAppNotificationModel,
    NotificationSummary,
    create_notification,
    bulk_create_notifications,
    query_user_notifications,
    mark_notification_as_read,
    mark_all_as_read,
    delete_notification,
    purge_old_notifications,
    get_unread_count,
)

__all__ = [
    # Auth User
    "AuthUserModel",
    "insert_auth_user",
    "query_auth_user_by_email",
    "query_auth_user_by_id",
    "query_auth_user_by_username",
    "query_all_auth_users",
    "query_active_auth_users",
    "update_auth_user_by_id",
    "deactivate_auth_user",
    # User
    "UserModel",
    "insert_user",
    "query_user_by_id",
    "query_all_users",
    "update_user_by_id",
    "drop_user_by_id",
    # Account
    "AccountModel",
    "AccountWithOwnerModel",
    "insert_account",
    "query_account_by_id",
    "query_all_accounts",
    "query_account_with_owner",
    "update_account",
    "deactivate_account",
    "activate_account",
    # Account User Association
    "AccountUserAssociationModel",
    "AccountUserWithDetailsModel",
    "BulkOperationResult",
    "add_user_to_account",
    "bulk_add_users_to_account",
    "update_user_role",
    "bulk_update_roles",
    "set_primary_account",
    "remove_user_from_account",
    "bulk_remove_users",
    "query_users_by_account",
    "query_accounts_by_user",
    "query_user_primary_account",
    "query_user_role_in_account",
    # Notification Preference
    "NotificationPreferenceModel",
    "create_default_preferences",
    "query_user_preferences",
    "update_user_preferences",
    "delete_user_preferences",
    "get_users_with_preference_enabled",
    # In-App Notification
    "InAppNotificationModel",
    "NotificationSummary",
    "create_notification",
    "bulk_create_notifications",
    "query_user_notifications",
    "mark_notification_as_read",
    "mark_all_as_read",
    "delete_notification",
    "purge_old_notifications",
    "get_unread_count",
]
