"""Add action table for selenium controller documentation

Revision ID: 14f5c85198e4
Revises: 77c8953606ea
Create Date: 2025-10-09 13:08:44.253573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f5c85198e4'
down_revision = '77c8953606ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_method', sa.String(length=255), nullable=True),
    sa.Column('action_documentation', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    # ### end Alembic commands ###
