"""change system_under_test owner_user_id FK to CASCADE

Revision ID: 41c97f44b5de
Revises: 750c1bd40831
Create Date: 2026-01-07 18:13:35.560304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c97f44b5de'
down_revision = '750c1bd40831'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('system_under_test_owner_user_id_fkey'), 'system_under_test', type_='foreignkey')
    op.create_foreign_key(None, 'system_under_test', 'auth_users', ['owner_user_id'], ['auth_user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_under_test', type_='foreignkey')
    op.create_foreign_key(op.f('system_under_test_owner_user_id_fkey'), 'system_under_test', 'auth_users', ['owner_user_id'], ['auth_user_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
