"""Remove test migration field

Revision ID: 574c7f2077e6
Revises: ff21978b9d56
Create Date: 2025-09-12 13:52:57.401944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574c7f2077e6'
down_revision = 'ff21978b9d56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'test_migration_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('test_migration_field', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
