"""major_schema_update_jan_2026_add_new_tables_soft_delete_and_relationships

Revision ID: 74cc10e65343
Revises: 14f5c85198e4
Create Date: 2026-01-06 16:58:28.572974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74cc10e65343'
down_revision = '14f5c85198e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('primary_contact', sa.String(length=36), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('account_name'),
    sa.UniqueConstraint('owner_user_id')
    )
    op.create_table('fenrir_actions',
    sa.Column('fenrir_action_id', sa.Integer(), nullable=False),
    sa.Column('method_name', sa.String(length=128), nullable=False),
    sa.Column('docstring', sa.Text(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('return_type', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('fenrir_action_id'),
    sa.UniqueConstraint('method_name')
    )
    op.create_table('audit_log',
    sa.Column('audit_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('performed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('idx_audit_account', 'audit_log', ['account_id'], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_pk', 'audit_log', ['audit_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_audit_sensitive', 'audit_log', ['is_sensitive', 'timestamp'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_user', 'audit_log', ['performed_by_user_id'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('token_id', sa.String(length=36), nullable=False),
    sa.Column('auth_user_id', sa.String(length=36), nullable=False),
    sa.Column('token_value', sa.String(length=64), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('token_expires_at > created_at', name='chk_token_expiry'),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.auth_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_value')
    )
    op.create_index('idx_auth_tokens_expires', 'auth_tokens', ['token_expires_at'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_auth_tokens_pk', 'auth_tokens', ['token_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_auth_tokens_user_active', 'auth_tokens', ['auth_user_id', 'is_active'], unique=False)
    op.create_index('idx_auth_tokens_value', 'auth_tokens', ['token_value'], unique=True)
    op.create_table('auth_user_account_association',
    sa.Column('association_id', sa.String(length=36), nullable=False),
    sa.Column('auth_user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.auth_user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('association_id'),
    sa.UniqueConstraint('auth_user_id', 'account_id', name='uq_user_account')
    )
    op.create_index('idx_user_account_account', 'auth_user_account_association', ['account_id'], unique=False)
    op.create_index('idx_user_account_active', 'auth_user_account_association', ['is_active'], unique=False)
    op.create_index('idx_user_account_user', 'auth_user_account_association', ['auth_user_id'], unique=False)
    op.create_table('entity_tag',
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('tag_name', sa.String(length=128), nullable=False),
    sa.Column('tag_category', sa.String(length=64), nullable=False),
    sa.Column('tag_value', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['auth_users.auth_user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deactivated_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'tag_name', 'account_id', name='uq_entitytag_entity_name_account')
    )
    op.create_index('idx_entitytag_account', 'entity_tag', ['account_id'], unique=False)
    op.create_index('idx_entitytag_account_category', 'entity_tag', ['account_id', 'tag_category'], unique=False)
    op.create_index('idx_entitytag_account_entity_category', 'entity_tag', ['account_id', 'entity_type', 'tag_category'], unique=False)
    op.create_index('idx_entitytag_active', 'entity_tag', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_entitytag_category', 'entity_tag', ['tag_category'], unique=False)
    op.create_index('idx_entitytag_entity', 'entity_tag', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_entitytag_entity_active', 'entity_tag', ['entity_type', 'entity_id', 'is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_entitytag_name', 'entity_tag', ['tag_name'], unique=False)
    op.create_index('idx_entitytag_pk', 'entity_tag', ['tag_id'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_entity_tag_account_id'), 'entity_tag', ['account_id'], unique=False)
    op.create_index(op.f('ix_entity_tag_entity_id'), 'entity_tag', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_tag_entity_type'), 'entity_tag', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_tag_tag_category'), 'entity_tag', ['tag_category'], unique=False)
    op.create_index(op.f('ix_entity_tag_tag_name'), 'entity_tag', ['tag_name'], unique=False)
    op.create_table('plan',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('plan_name', sa.String(length=255), nullable=False),
    sa.Column('suites_ids', sa.String(length=1024), nullable=False),
    sa.Column('suite_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='plan_status_enum'), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['deactivated_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index('idx_plan_account', 'plan', ['account_id'], unique=False)
    op.create_index('idx_plan_active', 'plan', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_plan_pk', 'plan', ['plan_id'], unique=False)
    op.create_table('system_under_test',
    sa.Column('sut_id', sa.String(length=36), nullable=False),
    sa.Column('system_name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('wiki_url', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deactivated_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.auth_user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sut_id'),
    sa.UniqueConstraint('system_name')
    )
    op.create_index('idx_sut_account', 'system_under_test', ['account_id'], unique=False)
    op.create_index('idx_sut_active', 'system_under_test', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_sut_pk', 'system_under_test', ['sut_id'], unique=False, postgresql_using='btree')
    op.create_table('action_chain',
    sa.Column('action_chain_id', sa.String(length=36), nullable=False),
    sa.Column('chain_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sut_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deactivated_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.auth_user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sut_id'], ['system_under_test.sut_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('action_chain_id'),
    sa.UniqueConstraint('chain_name')
    )
    op.create_index('idx_actionchain_account', 'action_chain', ['account_id'], unique=False)
    op.create_index('idx_actionchain_active', 'action_chain', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_actionchain_pk', 'action_chain', ['action_chain_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_actionchain_sut', 'action_chain', ['sut_id'], unique=False)
    op.create_table('page_fenrir_action_association',
    sa.Column('association_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('fenrir_action_id', sa.String(length=36), nullable=False),
    sa.Column('action_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fenrir_action_id'], ['fenrir_actions.fenrir_action_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['page.page_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('association_id')
    )
    op.create_index('idx_page_action_action', 'page_fenrir_action_association', ['fenrir_action_id'], unique=False)
    op.create_index('idx_page_action_order', 'page_fenrir_action_association', ['page_id', 'action_order'], unique=False)
    op.create_index('idx_page_action_page', 'page_fenrir_action_association', ['page_id'], unique=False)
    op.create_table('suite',
    sa.Column('suite_id', sa.String(length=36), nullable=False),
    sa.Column('suite_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sut_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deactivated_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.auth_user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sut_id'], ['system_under_test.sut_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('suite_id'),
    sa.UniqueConstraint('suite_name')
    )
    op.create_index('idx_suite_account', 'suite', ['account_id'], unique=False)
    op.create_index('idx_suite_active', 'suite', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_suite_pk', 'suite', ['suite_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_suite_sut', 'suite', ['sut_id'], unique=False)
    op.create_table('system_environment_association',
    sa.Column('association_id', sa.String(length=36), nullable=False),
    sa.Column('sut_id', sa.String(length=36), nullable=False),
    sa.Column('environment_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.environment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sut_id'], ['system_under_test.sut_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('association_id'),
    sa.UniqueConstraint('sut_id', 'environment_id', name='uq_system_environment')
    )
    op.create_index('idx_system_env_environment', 'system_environment_association', ['environment_id'], unique=False)
    op.create_index('idx_system_env_system', 'system_environment_association', ['sut_id'], unique=False)
    op.create_table('test_case',
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.String(length=64), nullable=False),
    sa.Column('sut_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deactivated_by_user_id'], ['auth_users.auth_user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.auth_user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sut_id'], ['system_under_test.sut_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_case_id'),
    sa.UniqueConstraint('test_name')
    )
    op.create_index('idx_testcase_account', 'test_case', ['account_id'], unique=False)
    op.create_index('idx_testcase_active', 'test_case', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_testcase_pk', 'test_case', ['test_case_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_testcase_sut', 'test_case', ['sut_id'], unique=False)
    op.create_index('idx_testcase_type', 'test_case', ['test_type'], unique=False)
    op.create_table('plan_suite_association',
    sa.Column('association_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('suite_id', sa.String(length=36), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.plan_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suite_id'], ['suite.suite_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('association_id')
    )
    op.create_index('idx_plan_suite_order', 'plan_suite_association', ['plan_id', 'execution_order'], unique=False)
    op.create_index('idx_plan_suite_plan', 'plan_suite_association', ['plan_id'], unique=False)
    op.create_index('idx_plan_suite_suite', 'plan_suite_association', ['suite_id'], unique=False)
    op.create_table('suite_test_case_association',
    sa.Column('association_id', sa.String(length=36), nullable=False),
    sa.Column('suite_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['suite.suite_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.test_case_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('association_id')
    )
    op.create_index('idx_suite_testcase_order', 'suite_test_case_association', ['suite_id', 'execution_order'], unique=False)
    op.create_index('idx_suite_testcase_suite', 'suite_test_case_association', ['suite_id'], unique=False)
    op.create_index('idx_suite_testcase_test', 'suite_test_case_association', ['test_case_id'], unique=False)
    op.drop_table('action')
    op.add_column('auth_users', sa.Column('auth_user_id', sa.Integer(), nullable=False))
    op.add_column('auth_users', sa.Column('auth_user_email', sa.String(length=255), nullable=False))
    op.add_column('auth_users', sa.Column('auth_username', sa.String(length=96), nullable=True))
    op.add_column('auth_users', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('auth_users', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('auth_users', sa.Column('current_auth_token', sa.String(length=64), nullable=True))
    op.add_column('auth_users', sa.Column('is_super_admin', sa.Boolean(), nullable=False))
    op.add_column('auth_users', sa.Column('multi_account_user', sa.Boolean(), nullable=False))
    op.add_column('auth_users', sa.Column('account_ids', sa.String(length=1024), nullable=True))
    op.add_column('auth_users', sa.Column('user_subscription_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('auth_users_email_key'), 'auth_users', type_='unique')
    op.create_unique_constraint(None, 'auth_users', ['auth_user_email'])
    op.drop_column('auth_users', 'email')
    op.drop_column('auth_users', 'username')
    op.drop_column('auth_users', 'id')
    op.drop_column('auth_users', 'current_token')
    op.add_column('emailProcessorTable', sa.Column('email_processor_id', sa.Integer(), nullable=False))
    op.drop_column('emailProcessorTable', 'id')
    op.add_column('environment', sa.Column('environment_id', sa.String(length=36), nullable=False))
    op.add_column('environment', sa.Column('environment_name', sa.String(length=96), nullable=False))
    op.add_column('environment', sa.Column('environment_base_url', sa.String(length=512), nullable=False))
    op.add_column('environment', sa.Column('api_base_url', sa.String(length=1024), nullable=True))
    op.add_column('environment', sa.Column('environment_status', sa.String(length=96), nullable=False))
    op.add_column('environment', sa.Column('users_in_environment', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('environment', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('environment', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('environment', sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True))
    op.drop_constraint(op.f('environment_name_key'), 'environment', type_='unique')
    op.create_index('idx_environment_active', 'environment', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_environment_pk', 'environment', ['environment_id'], unique=False, postgresql_using='btree')
    op.create_unique_constraint(None, 'environment', ['environment_id'])
    op.create_unique_constraint(None, 'environment', ['environment_name'])
    op.create_foreign_key(None, 'environment', 'auth_users', ['deactivated_by_user_id'], ['auth_user_id'], ondelete='SET NULL')
    op.drop_column('environment', 'name')
    op.drop_column('environment', 'status')
    op.drop_column('environment', 'users')
    op.drop_column('environment', 'id')
    op.drop_column('environment', 'url')
    op.drop_column('environment', 'api_url')
    op.add_column('identifier', sa.Column('identifier_id', sa.Integer(), nullable=False))
    op.add_column('identifier', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('identifier', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('identifier', sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True))
    op.create_index('idx_identifier_active', 'identifier', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_identifier_page', 'identifier', ['page_id'], unique=False)
    op.create_index('idx_identifier_pk', 'identifier', ['identifier_id'], unique=False)
    op.drop_constraint(op.f('identifier_page_id_fkey'), 'identifier', type_='foreignkey')
    op.create_foreign_key(None, 'identifier', 'page', ['page_id'], ['page_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'identifier', 'auth_users', ['deactivated_by_user_id'], ['auth_user_id'], ondelete='SET NULL')
    op.drop_column('identifier', 'action')
    op.drop_column('identifier', 'environments')
    op.drop_column('identifier', 'id')
    op.add_column('page', sa.Column('page_id', sa.Integer(), nullable=False))
    op.add_column('page', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('page', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('page', sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True))
    op.create_index('idx_page_active', 'page', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_page_pk', 'page', ['page_id'], unique=False)
    op.create_foreign_key(None, 'page', 'auth_users', ['deactivated_by_user_id'], ['auth_user_id'], ondelete='SET NULL')
    op.drop_column('page', 'id')
    op.add_column('user', sa.Column('sut_user_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('account_id', sa.String(length=36), nullable=True))
    op.add_column('user', sa.Column('sut_id', sa.String(length=36), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deactivated_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('deactivated_by_user_id', sa.String(length=36), nullable=True))
    op.create_index('idx_sut_user_account', 'user', ['account_id'], unique=False)
    op.create_index('idx_sut_user_active', 'user', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_sut_user_environment', 'user', ['environment_id'], unique=False)
    op.create_index('idx_sut_user_pk', 'user', ['sut_user_id'], unique=False)
    op.create_index('idx_sut_user_sut', 'user', ['sut_id'], unique=False)
    op.drop_constraint(op.f('user_environment_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'account', ['account_id'], ['account_id'])
    op.create_foreign_key(None, 'user', 'system_under_test', ['sut_id'], ['sut_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'environment', ['environment_id'], ['environment_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user', 'auth_users', ['deactivated_by_user_id'], ['auth_user_id'], ondelete='SET NULL')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_environment_id_fkey'), 'user', 'environment', ['environment_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_sut_user_sut', table_name='user')
    op.drop_index('idx_sut_user_pk', table_name='user')
    op.drop_index('idx_sut_user_environment', table_name='user')
    op.drop_index('idx_sut_user_active', table_name='user', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_sut_user_account', table_name='user')
    op.drop_column('user', 'deactivated_by_user_id')
    op.drop_column('user', 'deactivated_at')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'sut_id')
    op.drop_column('user', 'account_id')
    op.drop_column('user', 'sut_user_id')
    op.add_column('page', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'page', type_='foreignkey')
    op.drop_index('idx_page_pk', table_name='page')
    op.drop_index('idx_page_active', table_name='page', postgresql_where=sa.text('is_active = true'))
    op.drop_column('page', 'deactivated_by_user_id')
    op.drop_column('page', 'deactivated_at')
    op.drop_column('page', 'is_active')
    op.drop_column('page', 'page_id')
    op.add_column('identifier', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('identifier', sa.Column('environments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('identifier', sa.Column('action', sa.VARCHAR(length=96), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'identifier', type_='foreignkey')
    op.drop_constraint(None, 'identifier', type_='foreignkey')
    op.create_foreign_key(op.f('identifier_page_id_fkey'), 'identifier', 'page', ['page_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_identifier_pk', table_name='identifier')
    op.drop_index('idx_identifier_page', table_name='identifier')
    op.drop_index('idx_identifier_active', table_name='identifier', postgresql_where=sa.text('is_active = true'))
    op.drop_column('identifier', 'deactivated_by_user_id')
    op.drop_column('identifier', 'deactivated_at')
    op.drop_column('identifier', 'is_active')
    op.drop_column('identifier', 'identifier_id')
    op.add_column('environment', sa.Column('api_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('environment', sa.Column('url', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('environment', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('environment', sa.Column('users', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('environment', sa.Column('status', sa.VARCHAR(length=96), autoincrement=False, nullable=False))
    op.add_column('environment', sa.Column('name', sa.VARCHAR(length=96), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'environment', type_='foreignkey')
    op.drop_constraint(None, 'environment', type_='unique')
    op.drop_constraint(None, 'environment', type_='unique')
    op.drop_index('idx_environment_pk', table_name='environment', postgresql_using='btree')
    op.drop_index('idx_environment_active', table_name='environment', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('environment_name_key'), 'environment', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('environment', 'deactivated_by_user_id')
    op.drop_column('environment', 'deactivated_at')
    op.drop_column('environment', 'is_active')
    op.drop_column('environment', 'users_in_environment')
    op.drop_column('environment', 'environment_status')
    op.drop_column('environment', 'api_base_url')
    op.drop_column('environment', 'environment_base_url')
    op.drop_column('environment', 'environment_name')
    op.drop_column('environment', 'environment_id')
    op.add_column('emailProcessorTable', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('emailProcessorTable', 'email_processor_id')
    op.add_column('auth_users', sa.Column('current_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('auth_users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('auth_users', sa.Column('username', sa.VARCHAR(length=96), autoincrement=False, nullable=True))
    op.add_column('auth_users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'auth_users', type_='unique')
    op.create_unique_constraint(op.f('auth_users_email_key'), 'auth_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('auth_users', 'user_subscription_id')
    op.drop_column('auth_users', 'account_ids')
    op.drop_column('auth_users', 'multi_account_user')
    op.drop_column('auth_users', 'is_super_admin')
    op.drop_column('auth_users', 'current_auth_token')
    op.drop_column('auth_users', 'last_name')
    op.drop_column('auth_users', 'first_name')
    op.drop_column('auth_users', 'auth_username')
    op.drop_column('auth_users', 'auth_user_email')
    op.drop_column('auth_users', 'auth_user_id')
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('action_documentation', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('action_pkey'))
    )
    op.drop_index('idx_suite_testcase_test', table_name='suite_test_case_association')
    op.drop_index('idx_suite_testcase_suite', table_name='suite_test_case_association')
    op.drop_index('idx_suite_testcase_order', table_name='suite_test_case_association')
    op.drop_table('suite_test_case_association')
    op.drop_index('idx_plan_suite_suite', table_name='plan_suite_association')
    op.drop_index('idx_plan_suite_plan', table_name='plan_suite_association')
    op.drop_index('idx_plan_suite_order', table_name='plan_suite_association')
    op.drop_table('plan_suite_association')
    op.drop_index('idx_testcase_type', table_name='test_case')
    op.drop_index('idx_testcase_sut', table_name='test_case')
    op.drop_index('idx_testcase_pk', table_name='test_case', postgresql_using='btree')
    op.drop_index('idx_testcase_active', table_name='test_case', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_testcase_account', table_name='test_case')
    op.drop_table('test_case')
    op.drop_index('idx_system_env_system', table_name='system_environment_association')
    op.drop_index('idx_system_env_environment', table_name='system_environment_association')
    op.drop_table('system_environment_association')
    op.drop_index('idx_suite_sut', table_name='suite')
    op.drop_index('idx_suite_pk', table_name='suite', postgresql_using='btree')
    op.drop_index('idx_suite_active', table_name='suite', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_suite_account', table_name='suite')
    op.drop_table('suite')
    op.drop_index('idx_page_action_page', table_name='page_fenrir_action_association')
    op.drop_index('idx_page_action_order', table_name='page_fenrir_action_association')
    op.drop_index('idx_page_action_action', table_name='page_fenrir_action_association')
    op.drop_table('page_fenrir_action_association')
    op.drop_index('idx_actionchain_sut', table_name='action_chain')
    op.drop_index('idx_actionchain_pk', table_name='action_chain', postgresql_using='btree')
    op.drop_index('idx_actionchain_active', table_name='action_chain', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_actionchain_account', table_name='action_chain')
    op.drop_table('action_chain')
    op.drop_index('idx_sut_pk', table_name='system_under_test', postgresql_using='btree')
    op.drop_index('idx_sut_active', table_name='system_under_test', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_sut_account', table_name='system_under_test')
    op.drop_table('system_under_test')
    op.drop_index('idx_plan_pk', table_name='plan')
    op.drop_index('idx_plan_active', table_name='plan', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_plan_account', table_name='plan')
    op.drop_table('plan')
    op.drop_index(op.f('ix_entity_tag_tag_name'), table_name='entity_tag')
    op.drop_index(op.f('ix_entity_tag_tag_category'), table_name='entity_tag')
    op.drop_index(op.f('ix_entity_tag_entity_type'), table_name='entity_tag')
    op.drop_index(op.f('ix_entity_tag_entity_id'), table_name='entity_tag')
    op.drop_index(op.f('ix_entity_tag_account_id'), table_name='entity_tag')
    op.drop_index('idx_entitytag_pk', table_name='entity_tag', postgresql_using='btree')
    op.drop_index('idx_entitytag_name', table_name='entity_tag')
    op.drop_index('idx_entitytag_entity_active', table_name='entity_tag', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_entitytag_entity', table_name='entity_tag')
    op.drop_index('idx_entitytag_category', table_name='entity_tag')
    op.drop_index('idx_entitytag_active', table_name='entity_tag', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_entitytag_account_entity_category', table_name='entity_tag')
    op.drop_index('idx_entitytag_account_category', table_name='entity_tag')
    op.drop_index('idx_entitytag_account', table_name='entity_tag')
    op.drop_table('entity_tag')
    op.drop_index('idx_user_account_user', table_name='auth_user_account_association')
    op.drop_index('idx_user_account_active', table_name='auth_user_account_association')
    op.drop_index('idx_user_account_account', table_name='auth_user_account_association')
    op.drop_table('auth_user_account_association')
    op.drop_index('idx_auth_tokens_value', table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_user_active', table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_pk', table_name='auth_tokens', postgresql_using='btree')
    op.drop_index('idx_auth_tokens_expires', table_name='auth_tokens', postgresql_where=sa.text('is_active = true'))
    op.drop_table('auth_tokens')
    op.drop_index('idx_audit_user', table_name='audit_log')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_sensitive', table_name='audit_log')
    op.drop_index('idx_audit_pk', table_name='audit_log', postgresql_using='btree')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_account', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('fenrir_actions')
    op.drop_table('account')
    # ### end Alembic commands ###
