"""change account owner_user_id FK from RESTRICT to CASCADE

Revision ID: 750c1bd40831
Revises: a8de257b0f4f
Create Date: 2026-01-07 18:12:44.011750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750c1bd40831'
down_revision = 'a8de257b0f4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('account_owner_user_id_fkey'), 'account', type_='foreignkey')
    op.create_foreign_key(None, 'account', 'auth_users', ['owner_user_id'], ['auth_user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_foreign_key(op.f('account_owner_user_id_fkey'), 'account', 'auth_users', ['owner_user_id'], ['auth_user_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
