"""Add action field to identifiers and update page-identifier relationship

Revision ID: 77c8953606ea
Revises: c6a9dee90913
Create Date: 2025-09-30 16:16:28.034112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77c8953606ea'
down_revision = 'c6a9dee90913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identifier', sa.Column('action', sa.String(length=96), nullable=True))
    op.drop_column('page', 'identifiers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('identifiers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('identifier', 'action')
    # ### end Alembic commands ###
