"""remove unique constraint from account owner_user_id

Revision ID: a8de257b0f4f
Revises: 6bfb5f75709c
Create Date: 2026-01-07 18:11:33.169882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8de257b0f4f'
down_revision = '6bfb5f75709c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_under_test_user')
    op.drop_constraint(op.f('account_owner_user_id_key'), 'account', type_='unique')
    op.create_foreign_key(None, 'account', 'auth_users', ['owner_user_id'], ['auth_user_id'], ondelete='RESTRICT')
    op.drop_index(op.f('idx_auth_tokens_user'), table_name='auth_tokens')
    op.create_index('idx_auth_tokens_expires', 'auth_tokens', ['token_expires_at'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_auth_tokens_user_active', 'auth_tokens', ['auth_user_id', 'is_active'], unique=False)
    op.create_index('idx_auth_tokens_value', 'auth_tokens', ['token_value'], unique=True)
    op.create_foreign_key(None, 'auth_tokens', 'auth_users', ['auth_user_id'], ['auth_user_id'], ondelete='CASCADE')
    op.add_column('emailProcessorTable', sa.Column('email_processor_id', sa.Integer(), nullable=False))
    op.drop_column('emailProcessorTable', 'id')
    op.create_unique_constraint(None, 'environment', ['environment_id'])
    op.alter_column('purgeTable', 'last_purged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('purgeTable', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('purgeTable', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purgeTable', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('purgeTable', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('purgeTable', 'last_purged_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'environment', type_='unique')
    op.add_column('emailProcessorTable', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('emailProcessorTable', 'email_processor_id')
    op.drop_constraint(None, 'auth_tokens', type_='foreignkey')
    op.drop_index('idx_auth_tokens_value', table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_user_active', table_name='auth_tokens')
    op.drop_index('idx_auth_tokens_expires', table_name='auth_tokens', postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('idx_auth_tokens_user'), 'auth_tokens', ['auth_user_id'], unique=False)
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.create_unique_constraint(op.f('account_owner_user_id_key'), 'account', ['owner_user_id'], postgresql_nulls_not_distinct=False)
    op.create_table('system_under_test_user',
    sa.Column('sut_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('sut_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('added_by_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('sut_user_id', name=op.f('system_under_test_user_pkey'))
    )
    # ### end Alembic commands ###
