"""Add auth_users table and update existing models

Revision ID: c6a9dee90913
Revises: 001_initial_schema
Create Date: 2025-09-17 10:16:11.598632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6a9dee90913'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=96), nullable=True),
    sa.Column('current_token', sa.String(length=64), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.alter_column('emailProcessorTable', 'system',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'identifier', 'page', ['page_id'], ['id'], ondelete='CASCADE')
    op.add_column('page', sa.Column('page_url', sa.String(length=1024), nullable=False))
    op.alter_column('page', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'user', 'environment', ['environment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('page', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('page', 'page_url')
    op.drop_constraint(None, 'identifier', type_='foreignkey')
    op.alter_column('emailProcessorTable', 'system',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('auth_users')
    # ### end Alembic commands ###
