"""Initial schema from existing models

Revision ID: f427ef5ef811
Revises: 
Create Date: 2025-09-12 13:45:45.330267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f427ef5ef811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emailProcessorTable', 'multi_email_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('emailProcessorTable', 'multi_attachment_flag',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('emailProcessorTable', 'requires_processing',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_email_item_created_at'), table_name='emailProcessorTable')
    op.drop_index(op.f('idx_email_item_email_item_id'), table_name='emailProcessorTable')
    op.drop_index(op.f('idx_email_item_last_processed_at'), table_name='emailProcessorTable')
    op.drop_index(op.f('idx_email_item_requires_processing'), table_name='emailProcessorTable')
    op.drop_index(op.f('idx_email_item_system'), table_name='emailProcessorTable')
    op.alter_column('environment', 'users',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_environment_designation'), table_name='environment')
    op.drop_index(op.f('idx_environment_name'), table_name='environment')
    op.drop_index(op.f('idx_environment_status'), table_name='environment')
    op.alter_column('identifier', 'environments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_identifier_element_name'), table_name='identifier')
    op.drop_index(op.f('idx_identifier_locator_strategy'), table_name='identifier')
    op.drop_index(op.f('idx_identifier_page_id'), table_name='identifier')
    op.drop_index(op.f('idx_page_environments'), table_name='page', postgresql_using='gin')
    op.drop_index(op.f('idx_page_identifiers'), table_name='page', postgresql_using='gin')
    op.drop_index(op.f('idx_page_page_name'), table_name='page')
    op.drop_index(op.f('idx_user_email'), table_name='user')
    op.drop_index(op.f('idx_user_environment_id'), table_name='user')
    op.drop_index(op.f('idx_user_username'), table_name='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_username'), 'user', ['username'], unique=False)
    op.create_index(op.f('idx_user_environment_id'), 'user', ['environment_id'], unique=False)
    op.create_index(op.f('idx_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('idx_page_page_name'), 'page', ['page_name'], unique=False)
    op.create_index(op.f('idx_page_identifiers'), 'page', ['identifiers'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_page_environments'), 'page', ['environments'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_identifier_page_id'), 'identifier', ['page_id'], unique=False)
    op.create_index(op.f('idx_identifier_locator_strategy'), 'identifier', ['locator_strategy'], unique=False)
    op.create_index(op.f('idx_identifier_element_name'), 'identifier', ['element_name'], unique=False)
    op.alter_column('identifier', 'environments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_environment_status'), 'environment', ['status'], unique=False)
    op.create_index(op.f('idx_environment_name'), 'environment', ['name'], unique=False)
    op.create_index(op.f('idx_environment_designation'), 'environment', ['environment_designation'], unique=False)
    op.alter_column('environment', 'users',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_email_item_system'), 'emailProcessorTable', ['system'], unique=False)
    op.create_index(op.f('idx_email_item_requires_processing'), 'emailProcessorTable', ['requires_processing'], unique=False)
    op.create_index(op.f('idx_email_item_last_processed_at'), 'emailProcessorTable', ['last_processed_at'], unique=False)
    op.create_index(op.f('idx_email_item_email_item_id'), 'emailProcessorTable', ['email_item_id'], unique=False)
    op.create_index(op.f('idx_email_item_created_at'), 'emailProcessorTable', ['created_at'], unique=False)
    op.alter_column('emailProcessorTable', 'requires_processing',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('emailProcessorTable', 'multi_attachment_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('emailProcessorTable', 'multi_email_flag',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
