services:
  chrome:
    image: selenium/node-chrome:4.33.0-20250606
    platform: linux/amd64
    shm_size: 2gb
    depends_on: &id001
    - selenium-hub
    environment: &id002
    - SE_EVENT_BUS_HOST=selenium-hub
  selenium-hub:
    image: selenium/hub:4.33.0-20250606
    container_name: selenium-hub
    ports:
    - 4442:4442
    - 4443:4443
    - 4444:4444
    environment:
    - session-timeout=45
    - hub=http://localhost
  chrome-1:
    image: selenium/node-chrome:4.33.0-20250606
    platform: linux/amd64
    shm_size: 2gb
    depends_on: *id001
    environment: *id002
  chrome-2:
    image: selenium/node-chrome:4.33.0-20250606
    platform: linux/amd64
    shm_size: 2gb
    depends_on: *id001
    environment: *id002
